import 'package:flutter/material.dart';

const Color textColor = Color(0xff1D1E25);
const Color greyColor = Color(0xff808D9E);
const Color blackAccentColor = Color(0xff2B3453);
const Color cyanColor = Color(0xff59C3FF);
const Color whiteColor = Color(0xffFFFFFF);
const Color blackAccColor = Color(0xff191A26);
const Color silverColor = Color(0xffE9ECF2);
const Color greyAccentColor = Color(0xff9CA3AF);
const Color fillColor = Color(0xff12121D);
const Color softGreyColor = Color(0xffF8F8FB);
const Color gridentcyanColor = Color(0xff7BE7FF);
const Color gridentwhiteColor = Color(0xffF5FCFE);
const Color buttongredientcyan = Color(0xff088A8A);
const Color buttongredientscyan = Color(0xff36DADA);
const Color blackColor = Color(0xff000000);
const Color lightAccColor = Color(0xffE5E7EB);
const Color greenColor = Color(0xff48BD69);
const Color lightgreenColor = Color(0xffE8FFEE);
const Color logoColor = Color(0xffE6E9ED);
const Color greenAccentColor = Color(0xffD9F5E1);
const Color redColor = Color(0xffFF0000);
const Color darkpurpleColor = Color(0xff363853);
