// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukcT_5aTjgFzzL3k_BiuNuolc2pNXXQg',
    appId: '1:18006236700:web:765f9a4482703a65fc89d9',
    messagingSenderId: '18006236700',
    projectId: 'ehealthcare-3c515',
    authDomain: 'ehealthcare-3c515.firebaseapp.com',
    storageBucket: 'ehealthcare-3c515.appspot.com',
    measurementId: 'G-HM4B25WZ65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRzgu_dpk0O6Ec1gHiO1LTqxvsD-LaZU',
    appId: '1:18006236700:android:860229df884eb51bfc89d9',
    messagingSenderId: '18006236700',
    projectId: 'ehealthcare-3c515',
    storageBucket: 'ehealthcare-3c515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHPL2XGWhba_BleAJG1D-t5Ho1pFZhLs4',
    appId: '1:18006236700:ios:c19cfdc1c8bf27d0fc89d9',
    messagingSenderId: '18006236700',
    projectId: 'ehealthcare-3c515',
    storageBucket: 'ehealthcare-3c515.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHPL2XGWhba_BleAJG1D-t5Ho1pFZhLs4',
    appId: '1:18006236700:ios:c19cfdc1c8bf27d0fc89d9',
    messagingSenderId: '18006236700',
    projectId: 'ehealthcare-3c515',
    storageBucket: 'ehealthcare-3c515.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDukcT_5aTjgFzzL3k_BiuNuolc2pNXXQg',
    appId: '1:18006236700:web:fd22883b2357677dfc89d9',
    messagingSenderId: '18006236700',
    projectId: 'ehealthcare-3c515',
    authDomain: 'ehealthcare-3c515.firebaseapp.com',
    storageBucket: 'ehealthcare-3c515.appspot.com',
    measurementId: 'G-PGGHL6F7D9',
  );

}